2016_Training/QUINDIO/ICBF/ICBF/Controllers/DatninosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICBF.Models;

namespace ICBF.Controllers
{
    public class DatninosController : Controller
    {
        private baseicbfEntities db = new baseicbfEntities();

        // GET: Datninos
        public ActionResult Index()
        {
            var datninos = db.Datninos.Include(d => d.Dacudiente);
            return View(datninos.ToList());
        }

        // GET: Datninos/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datninos datninos = db.Datninos.Find(id);
            if (datninos == null)
            {
                return HttpNotFound();
            }
            return View(datninos);
        }

        // GET: Datninos/Create
        public ActionResult Create()
        {
            ViewBag.ide_acu = new SelectList(db.Dacudiente, "ide_acu", "nom_ape");
            return View();
        }

        // POST: Datninos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "niup,nomape,tip_san,ciu_nac,ide_acu,fec_nac,dir,tel,eps")] Datninos datninos)
        {
            if (ModelState.IsValid)
            {
                if (DateTime.Now<datninos.fec_nac.AddYears(6))
                {
                   db.Datninos.Add(datninos);
                    db.SaveChanges();
                    return RedirectToAction("Index"); 
                }
                else
                {
                    ViewBag.ide_acu = new SelectList(db.Dacudiente, "ide_acu", "nom_ape", datninos.ide_acu);
                    return View(datninos);
                }
                
            }

            ViewBag.ide_acu = new SelectList(db.Dacudiente, "ide_acu", "nom_ape", datninos.ide_acu);
            return View(datninos);
        }

        // GET: Datninos/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datninos datninos = db.Datninos.Find(id);
            if (datninos == null)
            {
                return HttpNotFound();
            }
            ViewBag.ide_acu = new SelectList(db.Dacudiente, "ide_acu", "nom_ape", datninos.ide_acu);
            return View(datninos);
        }

        // POST: Datninos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "niup,nomape,tip_san,ciu_nac,ide_acu,fec_nac,dir,tel,eps")] Datninos datninos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(datninos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ide_acu = new SelectList(db.Dacudiente, "ide_acu", "nom_ape", datninos.ide_acu);
            return View(datninos);
        }

        // GET: Datninos/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Datninos datninos = db.Datninos.Find(id);
            if (datninos == null)
            {
                return HttpNotFound();
            }
            return View(datninos);
        }

        // POST: Datninos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Datninos datninos = db.Datninos.Find(id);
            db.Datninos.Remove(datninos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2016_Training/QUINDIO/ICBF/ICBF/Controllers/RegNotasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ICBF.Models;

namespace ICBF.Controllers
{
    public class RegNotasController : Controller
    {
        private baseicbfEntities db = new baseicbfEntities();

        // GET: RegNotas
        public ActionResult Index()
        {
            var regNotas = db.RegNotas.Include(r => r.Datninos);
            return View(regNotas.ToList());
        }

        public ActionResult Index2()
        {
            var regNotas = db.RegNotas.Include(r => r.Datninos);
            return View(regNotas.ToList());
        }

        // GET: RegNotas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegNotas regNotas = db.RegNotas.Find(id);
            if (regNotas == null)
            {
                return HttpNotFound();
            }
            return View(regNotas);
        }

        // GET: RegNotas/Create
        public ActionResult Create()
        {
            ViewBag.niup = new SelectList(db.Datninos, "niup", "nomape");
            return View();
        }

        // POST: RegNotas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "niup,ano_escolar,nivel,nota,fec,observaciones")] RegNotas regNotas)
        {
            if (ModelState.IsValid)
            {
                db.RegNotas.Add(regNotas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.niup = new SelectList(db.Datninos, "niup", "nomape", regNotas.niup);
            return View(regNotas);
        }

        // GET: RegNotas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegNotas regNotas = db.RegNotas.Find(id);
            if (regNotas == null)
            {
                return HttpNotFound();
            }
            ViewBag.niup = new SelectList(db.Datninos, "niup", "nomape", regNotas.niup);
            return View(regNotas);
        }

        // POST: RegNotas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "niup,ano_escolar,nivel,nota,fec,observaciones")] RegNotas regNotas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(regNotas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.niup = new SelectList(db.Datninos, "niup", "nomape", regNotas.niup);
            return View(regNotas);
        }

        // GET: RegNotas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegNotas regNotas = db.RegNotas.Find(id);
            if (regNotas == null)
            {
                return HttpNotFound();
            }
            return View(regNotas);
        }

        // POST: RegNotas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            RegNotas regNotas = db.RegNotas.Find(id);
            db.RegNotas.Remove(regNotas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

2016_Training/QUINDIO/ICBF/ICBF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SENASOFT 2016</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema ICBF", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Administrador", "Index", "Datninos")</li>
                    <li>@Html.ActionLink("Madres", "Index", "regasistencias")</li>
                    <li>@Html.ActionLink("Acudientes", "Index2", "RegNotas")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - REGIONAL CESAR</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

2016_Training/QUINDIO/ICBF/ICBF/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema ICBF", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Niños", "Index", "Datninos")</li>
                    <li>@Html.ActionLink("Registrar Notas", "Index", "RegNotas")</li>
                    <li>@Html.ActionLink("Asignar Jardin", "Index", "asignacionjardins")</li>
                    <li>@Html.ActionLink("Madres", "Index", "DatMadreComunitarias")</li>
                    <li>@Html.ActionLink("Acudientes", "Index", "Dacudientes")</li>
                    <li>@Html.ActionLink("Jardines", "Index", "Regjardines")</li>
                    <li>@Html.ActionLink("Reportes Niños por Jardin", "Index", "NinosJardin")</li>
                    <li>@Html.ActionLink("Reportes Jardin Negados", "Index", "JardinesNoAprobados")</li>
                    <li>@Html.ActionLink("Reportes Inasistencias", "Index", "NinosEnfermos")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - REGIONAL CESAR</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>


2016_Training/QUINDIO/ICBF/ICBF/Views/Shared/_LayoutMadres.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema ICBF", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Registro de Asistencia", "Index", "regasistencias")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>